### DISCUSSION TITLE
TeslaBleHttpProxy + evcc + TWC gen 2 = battery drain?

### DISCUSSION THREAD

**Discussion by raymond79nl** [wimaha/TeslaBleHttpProxy#104] [Q&A] [answered]
Is there anyone here that uses TeslaBleHttpProxy + evcc, in combination with a TWC gen 2? 

All is working well, but with evcc active, my car has very significant battery drain. I installed TeslaMate to look into the details and it clearly shows that something is preventing the car to fall asleep, see state picture below (first part). When I shut down evcc plug-in in Home Assistant, the car immediately falls asleep (2nd part of the picture, after 19:50. I already disabled all other 3rd party connections to the car, but this check 'proofs' that something in my evcc config causes this behavior. 

![XkctUyImdF1QzjYoRj5ul8Ek](https://github.com/user-attachments/assets/595e7c39-0eae-4bd7-9366-0b163b782078)

```yaml
log: info
interval: 30s

mqtt:
  broker: [IP]:1883
  topic: evcc
  user: [USER]
  password: [PASSWD]

site:
  title: [HOME]
  meters:
    grid: my_grid
    pv:
      - solax

loadpoints:
  - title: Garage # display name for UI
    charger: my_charger # charger
    vehicle: tesla # default vehicle
    priority: 2
    soc:
      poll: # Force soc polling
        mode: charging
        interval: 60m
      estimate: true

meters:
[REMOVED ENERGY METER CONFIG AS I THINK IT'S IRRELEVANT FOR THIS DISCUSSION]

  - name: solax # Uitlezen Solax sensor HA, via modbus
    type: custom
    power:
      source: mqtt
      topic: homeassistant/sensor/solax_output_power/state
      timeout: 30s
      scale: 1000

chargers:
  - name: my_charger
    icon: car
    type: custom
    status:
      source: http
      uri: "http://[IP]:8080/api/1/vehicles/[VIN]/vehicle_data?endpoints=charge_state"
      method: GET
      jq: >
        if (.response.response.charge_state.charging_state == "Charging" 
            and .response.response.charge_state.charger_power > 0) then "C"
        elif (.response.response.charge_state.charging_state == "Charging") then "B"
        elif (.response.response.charge_state.charging_state == "Stopped") then "B"
        elif (.response.response.charge_state.charging_state == "NoPower") then "B"
        elif (.response.response.charge_state.charging_state == "Complete") then "B"
        elif (.response.response.charge_state.charging_state == "Starting") then "B"
        else "A" end
      timeout: 30s
    enabled:
      source: http
      uri: "http://[IP]:8080/api/1/vehicles/[VIN]/vehicle_data?endpoints=charge_state"
      method: GET
      jq: (.response.response.charge_state.charging_state == "Charging" and .response.response.charge_state.charger_power > 0)
      timeout: 30s
      cache: 25s
    enable:
      source: http
      uri: "http://[IP]:8080/api/1/vehicles/[VIN]/command/{{if .enable}}charge_start{{else}}charge_stop{{end}}"
      method: POST
      body: ""
      timeout: 30s
      cache: 25s
    maxcurrent:
      source: http
      uri: "http://[IP]:8080/api/1/vehicles/[VIN]/command/set_charging_amps"
      method: POST
      body: '{"charging_amps": "{{.maxcurrent}}"}'
      timeout: 30s

vehicles:
  - name: tesla
    type: template
    template: tesla-ble
    title: Tesla Model 3
    capacity: 49 # Akkukapazität in kWh (optional)
    vin: [VIN] # Erforderlich für BLE-Verbindung
    url: [IP] # URL des Tesla BLE HTTP Proxy
    port: 8080 # Port des Tesla BLE HTTP Proxy (optional)
    
tariffs: # See https://docs.evcc.io/docs/devices/tariffs#entso-e
[REMOVED]

```

**Comment by Poovarasan46** [comment]
It looks like evcc is keeping your Tesla awake, preventing it from entering sleep mode, which leads to battery drain. From your config, the likely culprit is the SOC polling in loadpoints:
Increase SOC polling interval
**Your config has:**
`soc:
  poll:
    mode: charging
    interval: 60m`

Try increasing the interval to 6+ hours (interval: 360m) or disabling polling entirely if you don’t need frequent updates.

**Disable MQTT Power Updates (if needed)**

- Your MQTT updates for solax have a timeout of 30s, which may be too frequent.
- If your vehicle polling depends on this, it could prevent sleep.

**Test by Temporarily Disabling Polling**
 
- Comment out the SOC polling and charger API calls.
- Restart evcc and check TeslaMate logs to see if the car falls asleep.

**Reply by raymond79nl** [reply]
Thanks for tips!

Removing the soc polling doesn't change anything in the behavior.

Commenting out the charger API calls did the trick and the car sleep behavior goes back to normal. Of course, in that situation I do not have a way to get charger status in evcc. I might have to look into using TeslaMate MQTT info (https://docs.teslamate.org/docs/integrations/mqtt/) for my custom charger. Have to figure out how to replace the code below to work with MQTT topic `teslamate/cars/1/charging_state`...

**Reply by dglaude** [reply]
I am not using TeslaBleHttpProxy, but a similar MQTT based solution.
Also I am not using the official Tesla vehicle template, but a custom.

But I am using Teslamate and I am getting SoC from it (and my car sleep OK).
So maybe you can use that part of my configuration...

Even if this is what I use (and it works fine), it should also possible to get the SoC in Bluetooth and not use Teslamate at all... the goal is to minimise the usage of the cloud API.

Good luck with your problem and here is the relevant part of my config:


```
vehicles:
- name: my_car           # reference to standard vehicle
  title: Tesla_Model_Y   # Will be displayed in the user interface (optional)
  type: custom
  capacity: 60
### tesla_ble_mqtt for max current and charge stop/start
  chargeenable:
    source: mqtt
    topic: tesla_ble/XP7YYYYY9YY999999/charging
    payload: '{{if .chargeenable}}start{{else}}stop{{end}}'
  maxcurrent: # set charger max current (A)
    source: mqtt
    topic: tesla_ble/XP7YYYYY9YY999999/charging-set-amps
    payload: '{{.maxcurrent}}'
  wakeup: # vehicle wake up command
    source: mqtt
    topic: tesla_ble/XP7YYYYY9YY999999/command
    payload: 'wake'
### Teslamate for SoC, range and status
  soc:
    source: mqtt
    topic: teslamate/cars/1/battery_level
    timeout: 8h
  range:
    source: mqtt
    topic: teslamate/cars/1/est_battery_range_km
    timeout: 8h
  status:

```
