### DISCUSSION TITLE
Minimum charging amps allowed by Tesla?

### DISCUSSION THREAD

**Discussion by svwhisper** [wimaha/TeslaBleHttpProxy#31] [General]
Before this week, I was able to set a charge rate of 2A.  That was the case for many months.  I updated the car to 2024.20.7 and now the minimum rate is 5A, even if my automation and the proxy commands "2A".  That makes a big difference for how well off-grid charging automation can work.

Has anyone else seen this change?  Of course, Tesla doesn't provide release notes to this level of detail.

**Comment by wimaha** [comment]
Are you using evcc?
I still don‘t have version 2024.20.7, so I can not verify that. If it‘s true it would be a shame…

**Comment by swa72** [comment]
I'm on 2024.20.7 and can still charge with <5A using EVCC .

**Comment by pssturges** [comment]
Have had the same issue since upgrading to 2024.26.7. Used to be able to dial it down to as little as 1A, now 5A is the minimum. TWC3 connected as 3-phase

**Comment by svwhisper** [comment]
It's strange, what is going on.  Now I can set the minimum to 2A and it works as it once did.  Very odd.  I'm 240V single phase.

**Comment by frandess** [comment]
Are you saying that you can charge your Tesla with TWC3 with less than 5A?
What do I have to do to make that work?

**Reply by swa72** [reply]
Using the newest version of EVCC and an older version of the Bluetooth proxy. No problems charging with less then 5A.

**Reply by frandess** [reply]
Would it be possible with the latest version of the proxy? Or which version do I need?
And which config do I need for evcc? Do I have to set minCurrent and what would be the minimal value?

My current one:
```
chargers:
- type: template
  template: twc3
  host: <>
  name: wallbox

vehicles:
- type: template
  template: tesla-ble
  title: <>
  vin: <>
  url: http://localhost
  port: 8080
  capacity: 78.1
  name: <>

loadpoints:
- title: Ladepunkt
  charger: wallbox
  vehicle: <> 
  enable:
    delay: 1m 
    threshold: -3600
  disable:
    delay: 4m
    threshold: 0
```
