### ISSUE TITLE
HA add-on and EVCC configuration

### ISSUE THREAD

**Issue by swa72** [wimaha/TeslaBleHttpProxy#40]
I charge two Teslas on my TWC and have an odd behaviour of EVCC's configuration using the HA add-on for EVCC.

Configuration works for T1 and **not** R1:

```
vehicles:
  # no spaces or special characters in the next line
  - name: T1
    type: template
    template: tesla
    commandProxy: http://192.168.178.78:8080/
    accessToken: XX
    refreshToken:  XX
    vin: XX
  - name: R1
    type: template
    template: tesla
    accessToken: XX
    refreshToken:  XX
    vin: XX
    commandProxy: http://192.168.178.78:8080/
```

Working for both vehicles:

```
vehicles:
  # no spaces or special characters in the next line
  - name: R1
    type: template
    template: tesla
    commandProxy: http://192.168.178.78:8080
    accessToken: XX
    refreshToken: XX
    vin: XX
  - name: T1
    type: template
    template: tesla
    commandProxy: http://192.168.178.78:8080
    accessToken: XX
    refreshToken: XX
    vin: XX
```
Note the position of  `commandProxy` in the configuration.

Maybe this is useful for others - I almost pulled my hair out until I discovered this ...
