### ISSUE TITLE
DISCUSSION - Full EVCC config

### ISSUE THREAD

**Issue by MrBLJ** [wimaha/TeslaBleHttpProxy#5]
>[!important]
> This is not an issue

Could you please provide your full EVCC config ? (discussions are not enabled, sorry for posting here)

**Comment by infinus** [comment]
Setup: EVCC and MQTT running on a raspberry pi. You will need to use Mqtt or some other integration to be able to pull the SOC of your car to make it work. Until I did this I could not get it to run out of EVCC. Since I already had a teslamate instance running I used that.

```
# open evcc at http://evcc.local:7070
network:
  schema: http
  host: evcc.local # .local suffix announces the hostname on MDNS
  port: 7070

log: info

# unique installation id
plant: *******

interval: 10s # control cycle interval

sponsortoken: *******

meters:
- type: template
  template: enphase
  usage: grid
  host: 192.168.1.225
  token: ******
  name: grid1

- type: template
  template: enphase
  usage: pv
  host: 192.168.1.225
  token: *****

chargers:
- type: template
  template: twc3
  host: 192.168.1.108
  name: TWC

vehicles:
- name: Infinus
  type: custom
  capacity: 74
  chargeenable:
    source: http
    uri: "http://192.168.1.17:8080/api/1/vehicles/*****/command/{{if .chargeenable}}charge_start{{else}}charge_stop{{end}}"
    method: POST
    body: ""
  maxcurrent: # set charger max current (A)
    source: http
    uri: http://192.168.1.17:8080/api/1/vehicles/*****/command/set_charging_amps
    method: POST
    body: '{"charging_amps": "{{.maxcurrent}}"}'
  wakeup: # vehicle wake up command
    source: http
    uri: http://192.168.1.17:8080/api/1/vehicles/*****/command/wake_up
    method: POST
    body: ""
  soc:
    source: mqtt
    topic: teslamate/cars/1/battery_level
    timeout: 60s
  range:
    source: mqtt
    topic: teslamate/cars/1/est_battery_range_km
    timeout: 60s
  status:
    source: combined
    plugged:
      source: mqtt
      topic: teslamate/cars/1/plugged_in
      timeout: 60s
    charging:
      source: mqtt
      topic: teslamate/cars/1/charging_state
      timeout: 60s

loadpoints:
- title: Home
  charger: TWC
  vehicle: Infinus
  mode: pv

mqtt:
  broker: localhost:1883

tariffs:
  currency: USD
  grid:
    # static grid price summer
    type: fixed
    price: 0.0925875 # [currency]/kWh
    zones:
      - days: Mo-Fr
        hours: 16-19
        price: 0.25797 # USD/kWh
      - days: Sa,So
        price: 0.0925875 # USD/kWh
    # Static grid price winter:
#    type: fixed
#    price: 0.0926325 # [currency]/kWh
#    zones:
#      - days: Mo-Fr
#        hours: 10-15
#        price: 0.0262125 # USD/kWh
#        hours: 16-19
#        price: 0.2440725 # USD/kWh
#      - days: Sa,So
#        price: 0.0926325 # USD/kWh

site:
  title: Home
  meters:
    grid: grid1
    pv:
    - pv1

```
