### ISSUE TITLE
Missing fields on dashboard

### ISSUE THREAD

**Issue by MrBLJ** [wimaha/TeslaBleHttpProxy#86]
I'm sorry if this sound very dumb, but I'm faced with a peculiar issue : I'm running the container using the docker comfiguration specified in the documentation (% logLevel and TZ) :

```yaml
services:
  tesla-ble-http-proxy:
    image: wimaha/tesla-ble-http-proxy
    container_name: TeslaBleHttpProxy
    environment:
      - cacheMaxAge=30
      - logLevel=debug
      - TZ=Europe/Paris
    volumes:
      - ~/TeslaBleHttpProxy/key:/key
      - /var/run/dbus:/var/run/dbus
    restart: always
    privileged: true
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
```

I can access the Web UI, but it's missing fields :
![image](https://github.com/user-attachments/assets/e4e46a8d-4b93-4919-a1d6-8438e428350e)

Logs are ok, I think, in portainer :

```
2025/01/13 15:51:45 INFO TeslaBleHttpProxy is loading ...
2025/01/13 15:51:45 DEBU LogLevel set to debug
2025/01/13 15:51:45 INFO TeslaBleHttpProxy is running!
```

Same using logs from cli :

```
root@DietPi:~/TeslaBleHttpProxy# docker logs --since 12h TeslaBleHttpProxy
2025/01/13 15:51:45 INFO TeslaBleHttpProxy is loading ...
2025/01/13 15:51:45 DEBU LogLevel set to debug
2025/01/13 15:51:45 INFO TeslaBleHttpProxy is running!
```

I tried recreating the container a few time, with system prune in between. Removing TZ and loglevel does not change anything.

I also tried using different browsers (firefox, brave, edge, safari on iOs) in regular and private browsing (0 extension). Same result.

The only thing I could find is a mention of a missing favicons, in my browser console's logs :

` GET http://192.168.20.149:8080/favicon.ico 404 (Not Found)`

I'm sorry to ask that but : Am I missing something obvious here ?
